name: Update README with daily quote
on:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with daily quote
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # MENGGUNAKAN ACTION PENGGANTI YANG AKTIF
      - uses: Gautam-Arora24/inspirational-quotes@v1
        with:
          # Tag di README.md HARUS SAMA dengan format ini
          quote_readme_tag: ""
