name: Update README with Joke
on:
  schedule:
    # Berjalan setiap 12 jam
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  joke:
    name: Update README with a new joke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ABSphreak/readme-jokes@v1
